version: '3.7'
services:
  hyperf:
    build: .
    links:
      - redis
      - mysql
    environment:
      - "APP_NAME=biz-skeleton"
      - "APP_ENV=test"
    ports:
      - 9501:9501
  redis:
    image: "redis:latest"
  mysql:
    build: .mysql/